version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: "nestjs"
      POSTGRES_USER: "nodejs"
      POSTGRES_PASSWORD: "nodejs"
      PGDATA: "./database:/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nodejs -d nestjs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "amir.bazanov.mess@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "amir.bazanov"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./database:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge